/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;


import java.awt.Color;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Sijan
 */
public class Database extends javax.swing.JFrame {

    /**
     * Creates new form Database
     */
    public Database() {
         initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("/icons/icon.png")).getImage());
        BufferedReader bw;
        try {
           
            bw = new BufferedReader(new FileReader(new File("config.txt")));
            host.setText(bw.readLine());
            port.setText(bw.readLine());
            user.setText(bw.readLine());
            pass.setText(bw.readLine());
            name.setText(bw.readLine());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        dbs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        openconf = new rojeru_san.complementos.RSButtonHover();
        rSLabelHora1 = new rojeru_san.rsdate.RSLabelHora();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        host = new javax.swing.JLabel();
        port = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        rSButtonRound1 = new rojeru_san.rsbutton.RSButtonRound();
        test = new rojeru_san.rsbutton.RSButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loginMouseDragged(evt);
            }
        });
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginMousePressed(evt);
            }
        });
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dbs.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        dbs.setForeground(new java.awt.Color(51, 102, 255));
        dbs.setText("Database Settings");
        login.add(dbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 0, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lifely.png"))); // NOI18N
        jLabel1.setText("Version 1.0");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, -1));

        jLabel7.setForeground(new java.awt.Color(62, 1, 1));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        login.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-390, 20, 760, -1));

        openconf.setText("Open Config File");
        openconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openconfActionPerformed(evt);
            }
        });
        login.add(openconf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));
        login.add(rSLabelHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 130, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Password:");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Current Settings:");
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Host:");
        login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Port:");
        login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Name:");
        login.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Username:");
        login.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        pass.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 0, 255));
        pass.setText("password");
        login.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 100, 20));

        host.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        host.setForeground(new java.awt.Color(0, 0, 255));
        host.setText("host");
        login.add(host, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, 20));

        port.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        port.setForeground(new java.awt.Color(0, 0, 255));
        port.setText("port");
        login.add(port, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 100, 20));

        name.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 255));
        name.setText("Name");
        login.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 100, 20));

        user.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        user.setForeground(new java.awt.Color(0, 0, 255));
        user.setText("Username");
        login.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 100, 20));

        rSButtonRound1.setText("Refresh");
        rSButtonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound1ActionPerformed(evt);
            }
        });
        login.add(rSButtonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 90, 20));

        test.setText("Test Connection");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });
        login.add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 160, 60));

        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_loginMouseDragged
int xx,xy;
    private void loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMousePressed
        xx = evt.getX();
        xy = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_loginMousePressed

    private void openconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openconfActionPerformed
if(!Desktop.isDesktopSupported())//check if Desktop is supported by Platform or not  
{  
System.out.println("not supported");
openconf.setText("Not supported");
}else{
    try {
        File file=new File("config.txt");
        Desktop desktop = Desktop.getDesktop();
        if(file.exists())
            desktop.open(file);
    } catch (IOException ex) {
        Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    }//GEN-LAST:event_openconfActionPerformed

    private void rSButtonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound1ActionPerformed
Database.main();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound1ActionPerformed

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
DB.isconf=1;
if(DB.getConnection()!=null){
    test.setText("Connected");
    Login.main();
    dispose();
}else{
   // test.setForeground(Color.red);
    test.setColorText(Color.red);
    test.setText("Not Connected");
}
DB.isconf=0;
    }//GEN-LAST:event_testActionPerformed

    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Database().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dbs;
    private javax.swing.JLabel host;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel login;
    private javax.swing.JLabel name;
    private rojeru_san.complementos.RSButtonHover openconf;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel port;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound1;
    private rojeru_san.rsdate.RSLabelHora rSLabelHora1;
    private rojeru_san.rsbutton.RSButtonRound test;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
