/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.awt.AWTException;
import java.awt.HeadlessException;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.MessageFormat;
import javax.swing.JTable;

/**
 *
 * @author prabinkokali
 */
public final class Events extends javax.swing.JFrame {
    /**
     * Creates new form Events
     */
    public Events() {
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/icon.png")).getImage());
        initComponents();
        jp1.setVisible(false);jp2.setVisible(false);jp3.setVisible(false);jp4.setVisible(false);jp5.setVisible(false);
        upDateDB();
        avatar.setImage(new ImageIcon(Getuserpic.image));
        //id.setText(bw.readLine());
        name.setText(getUserData.fname+" "+getUserData.lname);
        
    }
    PreparedStatement pst;ResultSet rs;int q,i;
   public void upDateDB() {
        try {
                
            id = UserDB.getUserID();
            
            pst = DB.getConnection().prepareStatement("select * from events where UID=" + id);

            rs = pst.executeQuery();
            ResultSetMetaData StData = rs.getMetaData();

            q = StData.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel) tn.getModel();
            RecordTable.setRowCount(0);

            while (rs.next()) {

                Vector columnData = new Vector();

                for (i = 1; i <= q; i++) {
                    columnData.add(rs.getInt("ID"));
                    columnData.add(rs.getString("Event_name"));
                   // columnData.add(rs.getString("Note"));
                    columnData.add(rs.getString("Date"));
                }
                RecordTable.addRow(columnData);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
    
void hideedit(){
    ed1.setVisible(false);
        ed2.setVisible(false);
        ed3.setVisible(false);
        ed4.setVisible(false);
        ed5.setVisible(false);
}
void showedit(int c){
    switch(c){
        case 1:
            hideedit();
            ed1.setVisible(true);
            break;
        case 2:
            hideedit();
            ed2.setVisible(true);
            break;
        case 3:
            hideedit();
            ed3.setVisible(true);
            break;
        case 4:
            hideedit();
            ed4.setVisible(true);
            break;
        case 5:
            hideedit();
            ed5.setVisible(true);
            break;
        default:
            hideedit();
            break;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        avatar = new home.ImageAvatar();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        rSButtonRound7 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound6 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound3 = new rojeru_san.rsbutton.RSButtonRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tn = new rojeru_san.complementos.TableMetro();
        subject = new RSMaterialComponent.RSTextFieldMaterial();
        datee = new rojeru_san.rsdate.RSDateChooser();
        add = new rojeru_san.rsbutton.RSButtonRound();
        update = new rojeru_san.rsbutton.RSButtonRound();
        delete = new rojeru_san.rsbutton.RSButtonRound();
        print = new rojeru_san.rsbutton.RSButtonRound();
        jp1 = new javax.swing.JPanel();
        ed2 = new javax.swing.JPanel();
        rSButtonRound25 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound26 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound27 = new rojeru_san.rsbutton.RSButtonRound();
        daysleft1 = new javax.swing.JLabel();
        e2 = new javax.swing.JLabel();
        previous = new rojeru_san.rsbutton.RSButtonRound();
        nxt = new rojeru_san.rsbutton.RSButtonRound();
        jPanel6 = new javax.swing.JPanel();
        jp2 = new javax.swing.JPanel();
        ed3 = new javax.swing.JPanel();
        rSButtonRound31 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound32 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound33 = new rojeru_san.rsbutton.RSButtonRound();
        daysleft2 = new javax.swing.JLabel();
        e3 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        ed5 = new javax.swing.JPanel();
        rSButtonRound18 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound19 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound20 = new rojeru_san.rsbutton.RSButtonRound();
        daysleft4 = new javax.swing.JLabel();
        e5 = new javax.swing.JLabel();
        jp4 = new javax.swing.JPanel();
        ed4 = new javax.swing.JPanel();
        rSButtonRound28 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound29 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound30 = new rojeru_san.rsbutton.RSButtonRound();
        daysleft3 = new javax.swing.JLabel();
        e4 = new javax.swing.JLabel();
        jp5 = new javax.swing.JPanel();
        ed1 = new javax.swing.JPanel();
        rSButtonRound22 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound23 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound24 = new rojeru_san.rsbutton.RSButtonRound();
        e1 = new javax.swing.JLabel();
        daysleft = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Events");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setMinimumSize(new java.awt.Dimension(705, 401));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        avatar.setImage(new javax.swing.ImageIcon(getClass().getResource("/icons/usrimg.PNG"))); // NOI18N
        avatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avatarMouseClicked(evt);
            }
        });
        jPanel1.add(avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lifely.png"))); // NOI18N
        jLabel1.setText("Version 1.0");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 50));

        name.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(29, 161, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name.setText("Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 250, 40));

        rSButtonRound7.setText("Contact Us");
        rSButtonRound7.setBorderPainted(false);
        rSButtonRound7.setFocusable(false);
        rSButtonRound7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound7ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 110, 30));

        rSButtonRound6.setText("Back");
        rSButtonRound6.setBorderPainted(false);
        rSButtonRound6.setFocusable(false);
        rSButtonRound6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 80, 30));

        rSButtonRound3.setText("Refresh");
        rSButtonRound3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 110, 30));

        jLabel2.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 144, 250));
        jLabel2.setText("Events");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 90, 50));

        jLabel7.setForeground(new java.awt.Color(62, 1, 1));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 39, -1, 20));

        tn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Event", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tn.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tn.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tn.setDragEnabled(true);
        tn.setRowHeight(30);
        tn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tnMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tn);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 620, 410));

        subject.setPlaceholder("Enter Event");
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        jPanel1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 60));

        datee.setLanguage(rojeru_san.rsdate.RSDateChooser.Language.ENGLISH);
        datee.setPlaceholder("Select Date");
        jPanel1.add(datee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, -1));

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 110, -1));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 90, -1));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 90, -1));

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 470));

        jp1.setBackground(new java.awt.Color(222, 227, 249));
        jp1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        jp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ed2.setBackground(new java.awt.Color(222, 227, 249));
        ed2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        ed2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound25.setText("Edit");
        rSButtonRound25.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        ed2.add(rSButtonRound25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 20));

        rSButtonRound26.setText("Delete");
        rSButtonRound26.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound26ActionPerformed(evt);
            }
        });
        ed2.add(rSButtonRound26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 20));

        rSButtonRound27.setText("Done");
        rSButtonRound27.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound27ActionPerformed(evt);
            }
        });
        ed2.add(rSButtonRound27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jp1.add(ed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 40));

        daysleft1.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        daysleft1.setForeground(new java.awt.Color(52, 170, 231));
        daysleft1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daysleft1.setText("O days left");
        daysleft1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)), new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true)));
        daysleft1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daysleft1MouseEntered(evt);
            }
        });
        jp1.add(daysleft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 120, 40));

        e2.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        e2.setForeground(new java.awt.Color(52, 170, 231));
        e2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e2.setText("Event 2");
        e2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e2MouseEntered(evt);
            }
        });
        jp1.add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        getContentPane().add(jp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        previous.setText("Previous");
        previous.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        getContentPane().add(previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 110, 20));

        nxt.setText("Next");
        nxt.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtActionPerformed(evt);
            }
        });
        getContentPane().add(nxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 90, 20));

        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 630, 410));

        jp2.setBackground(new java.awt.Color(222, 227, 249));
        jp2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        jp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ed3.setBackground(new java.awt.Color(222, 227, 249));
        ed3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        ed3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound31.setText("Edit");
        rSButtonRound31.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        ed3.add(rSButtonRound31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 20));

        rSButtonRound32.setText("Delete");
        rSButtonRound32.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound32ActionPerformed(evt);
            }
        });
        ed3.add(rSButtonRound32, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 20));

        rSButtonRound33.setText("Done");
        rSButtonRound33.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound33ActionPerformed(evt);
            }
        });
        ed3.add(rSButtonRound33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jp2.add(ed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 40));

        daysleft2.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        daysleft2.setForeground(new java.awt.Color(52, 170, 231));
        daysleft2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daysleft2.setText("O days left");
        daysleft2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)), new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true)));
        daysleft2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daysleft2MouseEntered(evt);
            }
        });
        jp2.add(daysleft2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 120, 40));

        e3.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        e3.setForeground(new java.awt.Color(52, 170, 231));
        e3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e3.setText("Event 3");
        e3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e3MouseEntered(evt);
            }
        });
        jp2.add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        getContentPane().add(jp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jp3.setBackground(new java.awt.Color(222, 227, 249));
        jp3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        jp3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ed5.setBackground(new java.awt.Color(222, 227, 249));
        ed5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        ed5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound18.setText("Edit");
        rSButtonRound18.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        ed5.add(rSButtonRound18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 20));

        rSButtonRound19.setText("Delete");
        rSButtonRound19.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound19ActionPerformed(evt);
            }
        });
        ed5.add(rSButtonRound19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 20));

        rSButtonRound20.setText("Done");
        rSButtonRound20.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound20ActionPerformed(evt);
            }
        });
        ed5.add(rSButtonRound20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jp3.add(ed5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 40));

        daysleft4.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        daysleft4.setForeground(new java.awt.Color(52, 170, 231));
        daysleft4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daysleft4.setText("O days left");
        daysleft4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)), new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true)));
        daysleft4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daysleft4MouseEntered(evt);
            }
        });
        jp3.add(daysleft4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 120, 40));

        e5.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        e5.setForeground(new java.awt.Color(52, 170, 231));
        e5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e5.setText("Event 5");
        e5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e5MouseEntered(evt);
            }
        });
        jp3.add(e5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 40));

        getContentPane().add(jp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jp4.setBackground(new java.awt.Color(222, 227, 249));
        jp4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        jp4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ed4.setBackground(new java.awt.Color(222, 227, 249));
        ed4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        ed4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound28.setText("Edit");
        rSButtonRound28.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        ed4.add(rSButtonRound28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 20));

        rSButtonRound29.setText("Delete");
        rSButtonRound29.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound29ActionPerformed(evt);
            }
        });
        ed4.add(rSButtonRound29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 20));

        rSButtonRound30.setText("Done");
        rSButtonRound30.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound30ActionPerformed(evt);
            }
        });
        ed4.add(rSButtonRound30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jp4.add(ed4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 40));

        daysleft3.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        daysleft3.setForeground(new java.awt.Color(52, 170, 231));
        daysleft3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daysleft3.setText("O days left");
        daysleft3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)), new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true)));
        daysleft3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daysleft3MouseEntered(evt);
            }
        });
        jp4.add(daysleft3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 120, 40));

        e4.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        e4.setForeground(new java.awt.Color(52, 170, 231));
        e4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e4.setText("Event 4");
        e4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e4MouseEntered(evt);
            }
        });
        jp4.add(e4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        getContentPane().add(jp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jp5.setBackground(new java.awt.Color(222, 227, 249));
        jp5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        jp5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ed1.setBackground(new java.awt.Color(222, 227, 249));
        ed1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        ed1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound22.setText("Edit");
        rSButtonRound22.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound22ActionPerformed(evt);
            }
        });
        ed1.add(rSButtonRound22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 20));

        rSButtonRound23.setText("Delete");
        rSButtonRound23.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound23ActionPerformed(evt);
            }
        });
        ed1.add(rSButtonRound23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 20));

        rSButtonRound24.setText("Done");
        rSButtonRound24.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound24ActionPerformed(evt);
            }
        });
        ed1.add(rSButtonRound24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jp5.add(ed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 40));

        e1.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        e1.setForeground(new java.awt.Color(52, 170, 231));
        e1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e1.setText("Event 1");
        e1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e1MouseEntered(evt);
            }
        });
        jp5.add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        daysleft.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        daysleft.setForeground(new java.awt.Color(52, 170, 231));
        daysleft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daysleft.setText("O days left");
        daysleft.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)), new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true)));
        daysleft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daysleftMouseEntered(evt);
            }
        });
        jp5.add(daysleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 120, 40));

        getContentPane().add(jp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRound7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound7ActionPerformed
        Contact.main();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound7ActionPerformed

    private void rSButtonRound6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound6ActionPerformed
        Dash.main();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound6ActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_previousActionPerformed

    private void rSButtonRound20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound20ActionPerformed

    private void nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtActionPerformed

    }//GEN-LAST:event_nxtActionPerformed

    private void rSButtonRound19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound19ActionPerformed

    private void rSButtonRound23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound23ActionPerformed

    private void rSButtonRound24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound24ActionPerformed

    private void rSButtonRound26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound26ActionPerformed

    private void rSButtonRound27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound27ActionPerformed

    private void rSButtonRound29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound29ActionPerformed

    private void rSButtonRound30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound30ActionPerformed

    private void rSButtonRound32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound32ActionPerformed

    private void rSButtonRound33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound33ActionPerformed

    private void e1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1MouseEntered
showedit(1);        // TODO add your handling code here:
    }//GEN-LAST:event_e1MouseEntered

    private void e2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2MouseEntered
showedit(2);        // TODO add your handling code here:
    }//GEN-LAST:event_e2MouseEntered

    private void e3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3MouseEntered
showedit(3);        // TODO add your handling code here:
    }//GEN-LAST:event_e3MouseEntered

    private void e4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e4MouseEntered
showedit(4);        // TODO add your handling code here:
    }//GEN-LAST:event_e4MouseEntered

    private void e5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e5MouseEntered
showedit(5);        // TODO add your handling code here:
    }//GEN-LAST:event_e5MouseEntered

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
hideedit();        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void rSButtonRound22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound22ActionPerformed
       // EventEdit.title="Edit Event";
       // EventEdit.task="Edit";
       // EventEdit.main();         // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound22ActionPerformed

    private void daysleftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daysleftMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_daysleftMouseEntered

    private void daysleft1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daysleft1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_daysleft1MouseEntered

    private void daysleft2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daysleft2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_daysleft2MouseEntered

    private void daysleft3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daysleft3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_daysleft3MouseEntered

    private void daysleft4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daysleft4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_daysleft4MouseEntered

    private void rSButtonRound3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound3ActionPerformed
        Events.main();
        dispose();
    }//GEN-LAST:event_rSButtonRound3ActionPerformed

    private void e1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1MouseClicked

    }//GEN-LAST:event_e1MouseClicked
int eventid;
    private void tnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tnMouseClicked
        try {
            // if (!tn.isRowSelected(0 - 2000)) {
                //     JOptionPane.showMessageDialog(this, "note is not selected");
                /// } else {
                DefaultTableModel RecordTable = (DefaultTableModel) tn.getModel();
                int SelectedRows = tn.getSelectedRow();
                eventid = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
                subject.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
                //note.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy/mm/dd");
                String d = RecordTable.getValueAt(SelectedRows, 2).toString();
                Date dd;
                dd = (Date) formatter.parse(d);
                datee.setDatoFecha(dd);
                //jtxtPostCode.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
                //jtxtTelephone.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
                // }
        } catch (ParseException ex) {
            Logger.getLogger(Note.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tnMouseClicked

    private void tnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tnMousePressed
        //delete.doClick();

        // TODO add your handling code here:
    }//GEN-LAST:event_tnMousePressed

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed
int id;
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if (subject.getText().equals("")) {
            Toaster t = new Toaster(jPanel1);
            t.error("Please enter data first");
        } else {
            try {

                pst = DB.getConnection().prepareStatement("insert into events(UID,Event_name,Date)value(?,?,?)");
                id = UserDB.getUserID();
                System.out.println(id);
                pst.setInt(1, id);
                pst.setString(2, subject.getText());
               // pst.setString(3, note.getText());
                pst.setString(3, datee.getDatoFecha().getYear() + 1900 + "/" + (datee.getDatoFecha().getMonth() + 1) + "/" + datee.getDatoFecha().getDate());
                pst.executeUpdate();
               // JOptionPane.showMessageDialog(this, "New Event Added");
                upDateDB();
            } //
            catch (SQLException ex) {
                System.err.println(ex);
            } catch (HeadlessException ex) {
                Logger.getLogger(Note.class.getName()).log(Level.SEVERE, null, ex);
            }            //tn.add
        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel) tn.getModel();
        int SelectedRows = tn.getSelectedRow();

        try {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            pst = DB.getConnection().prepareStatement("update events set Event_name = ?, Date=? where id =?");
            pst.setString(1, subject.getText());
            //pst.setString(2, note.getText());
            pst.setString(2, datee.getDatoFecha().getYear() + 1900 + "/" + (datee.getDatoFecha().getMonth() + 1) + "/" + datee.getDatoFecha().getDate());
            pst.setInt(3, eventid);

            pst.executeUpdate();
            //JOptionPane.showMessageDialog(this, "Event Updated");
            upDateDB();
            subject.setText("");
           // note.setText("");
        } catch (SQLException ex) {

            System.err.println(ex);
        } catch (HeadlessException | NumberFormatException ex) {
            Logger.getLogger(Note.class.getName()).log(Level.SEVERE, null, ex);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel) tn.getModel();
        int SelectedRows = tn.getSelectedRow();

        try {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            int deleteItem;
            deleteItem = JOptionPane.showConfirmDialog(null, "Confirm if you want to delete Event",
                "Warning", JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION) {

                pst = DB.getConnection().prepareStatement("delete from events where id =?");

                pst.setInt(1, id);
                pst.executeUpdate();
                //JOptionPane.showMessageDialog(this, "Record updated");
                upDateDB();

                subject.setText("");
               // note.setText("");
                subject.requestFocus();

            }

        } catch (SQLException ex) {
            System.err.println(ex);

        } catch (HeadlessException | NumberFormatException ex) {
            Logger.getLogger(Note.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header = new MessageFormat("Events in Lifely: "+getUserData.fname+" "+getUserData.lname);
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");

        try {
            tn.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("No Printer found", e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void avatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avatarMouseClicked
        Userprofile.main();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_avatarMouseClicked

    /**
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Events().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsbutton.RSButtonRound add;
    private home.ImageAvatar avatar;
    private rojeru_san.rsdate.RSDateChooser datee;
    private javax.swing.JLabel daysleft;
    private javax.swing.JLabel daysleft1;
    private javax.swing.JLabel daysleft2;
    private javax.swing.JLabel daysleft3;
    private javax.swing.JLabel daysleft4;
    private rojeru_san.rsbutton.RSButtonRound delete;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel e3;
    private javax.swing.JLabel e4;
    private javax.swing.JLabel e5;
    private javax.swing.JPanel ed1;
    private javax.swing.JPanel ed2;
    private javax.swing.JPanel ed3;
    private javax.swing.JPanel ed4;
    private javax.swing.JPanel ed5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jp5;
    private javax.swing.JLabel name;
    private rojeru_san.rsbutton.RSButtonRound nxt;
    private rojeru_san.rsbutton.RSButtonRound previous;
    private rojeru_san.rsbutton.RSButtonRound print;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound18;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound19;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound20;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound22;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound23;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound24;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound25;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound26;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound27;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound28;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound29;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound3;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound30;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound31;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound32;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound33;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound6;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound7;
    private RSMaterialComponent.RSTextFieldMaterial subject;
    private rojeru_san.complementos.TableMetro tn;
    private rojeru_san.rsbutton.RSButtonRound update;
    // End of variables declaration//GEN-END:variables
}
