/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.awt.AWTException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author prabinkokali
 */
public class Events extends javax.swing.JFrame {
    /**
     * Creates new form Events
     */
    public Events() {this.setIconImage(new ImageIcon(getClass().getResource("/icons/icon.png")).getImage());
        initComponents();
        //id.setText(bw.readLine());
        try (BufferedReader bw = new BufferedReader(new FileReader(new File("user.txt")))) {
            bw.readLine();
            name.setText(Crypt.decrypt(bw.readLine())+" "+Crypt.decrypt(bw.readLine()));
        } catch (Exception ex) {
            Logger.getLogger(Events.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    int[] EventUID;
    String[] EventTitle;
    String[] EventDetails;
    String[] EventDate;
    int next=0;
    void next(){
        
    }
    void FetchEvent(){
    try {
        PreparedStatement ps;
            String queryString = "SELECT * FROM `events` WHERE UID='" + new UserDB().id;
            ps = DB.getConnection().prepareStatement(queryString);
            try ( ResultSet results = ps.executeQuery()) {
                int i=1;
                while(results.next()) {
                    EventUID[i]=results.getInt("UID");
                    EventTitle[i]=results.getString("Event_name");
                    EventDetails[i]=results.getString("Event_details");
                    EventDate[i]=results.getString("date");
                }
                
            }
    } catch (SQLException ex) {
        Logger.getLogger(Events.class.getName()).log(Level.SEVERE, null, ex);
    } catch (Exception ex) {
        Logger.getLogger(Events.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
void hideedit(){
    ed1.setVisible(false);
        ed2.setVisible(false);
        ed3.setVisible(false);
        ed4.setVisible(false);
        ed5.setVisible(false);
}
void showedit(int c){
    switch(c){
        case 1:
            hideedit();
            ed1.setVisible(true);
            break;
        case 2:
            hideedit();
            ed2.setVisible(true);
            break;
        case 3:
            hideedit();
            ed3.setVisible(true);
            break;
        case 4:
            hideedit();
            ed4.setVisible(true);
            break;
        case 5:
            hideedit();
            ed5.setVisible(true);
            break;
        default:
            hideedit();
            break;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        rSButtonRound1 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound7 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound6 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound3 = new rojeru_san.rsbutton.RSButtonRound();
        jPanel3 = new javax.swing.JPanel();
        ed1 = new javax.swing.JPanel();
        rSButtonRound22 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound23 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound24 = new rojeru_san.rsbutton.RSButtonRound();
        e1 = new javax.swing.JLabel();
        daysleft = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ed4 = new javax.swing.JPanel();
        rSButtonRound28 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound29 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound30 = new rojeru_san.rsbutton.RSButtonRound();
        daysleft3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        ed5 = new javax.swing.JPanel();
        rSButtonRound18 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound19 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound20 = new rojeru_san.rsbutton.RSButtonRound();
        daysleft4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ed3 = new javax.swing.JPanel();
        rSButtonRound31 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound32 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound33 = new rojeru_san.rsbutton.RSButtonRound();
        daysleft2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ed2 = new javax.swing.JPanel();
        rSButtonRound25 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound26 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound27 = new rojeru_san.rsbutton.RSButtonRound();
        daysleft1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rSButtonRound17 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound21 = new rojeru_san.rsbutton.RSButtonRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rSButtonRound4 = new rojeru_san.rsbutton.RSButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Events");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setMinimumSize(new java.awt.Dimension(705, 401));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lifely.png"))); // NOI18N
        jLabel1.setText("Version 1.0");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 50));

        name.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(29, 161, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name.setText("Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 230, 30));

        rSButtonRound1.setText("Log Out");
        rSButtonRound1.setBorderPainted(false);
        rSButtonRound1.setFocusable(false);
        rSButtonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 90, 30));

        rSButtonRound7.setText("Contact Us");
        rSButtonRound7.setBorderPainted(false);
        rSButtonRound7.setFocusable(false);
        rSButtonRound7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound7ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 110, 30));

        rSButtonRound6.setText("Back");
        rSButtonRound6.setBorderPainted(false);
        rSButtonRound6.setFocusable(false);
        rSButtonRound6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 80, 30));

        rSButtonRound3.setText("Refresh");
        rSButtonRound3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, 30));

        jPanel3.setBackground(new java.awt.Color(222, 227, 249));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ed1.setBackground(new java.awt.Color(222, 227, 249));
        ed1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        ed1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound22.setText("Edit");
        rSButtonRound22.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound22ActionPerformed(evt);
            }
        });
        ed1.add(rSButtonRound22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 20));

        rSButtonRound23.setText("Delete");
        rSButtonRound23.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound23ActionPerformed(evt);
            }
        });
        ed1.add(rSButtonRound23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 20));

        rSButtonRound24.setText("Done");
        rSButtonRound24.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound24ActionPerformed(evt);
            }
        });
        ed1.add(rSButtonRound24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jPanel3.add(ed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 40));

        e1.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        e1.setForeground(new java.awt.Color(52, 170, 231));
        e1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e1.setText("Event 1");
        e1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                e1MouseEntered(evt);
            }
        });
        jPanel3.add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        daysleft.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        daysleft.setForeground(new java.awt.Color(52, 170, 231));
        daysleft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daysleft.setText("O days left");
        daysleft.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)), new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true)));
        daysleft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daysleftMouseEntered(evt);
            }
        });
        jPanel3.add(daysleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 120, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 640, 40));

        jPanel5.setBackground(new java.awt.Color(222, 227, 249));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ed4.setBackground(new java.awt.Color(222, 227, 249));
        ed4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        ed4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound28.setText("Edit");
        rSButtonRound28.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        ed4.add(rSButtonRound28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 20));

        rSButtonRound29.setText("Delete");
        rSButtonRound29.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound29ActionPerformed(evt);
            }
        });
        ed4.add(rSButtonRound29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 20));

        rSButtonRound30.setText("Done");
        rSButtonRound30.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound30ActionPerformed(evt);
            }
        });
        ed4.add(rSButtonRound30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jPanel5.add(ed4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 40));

        daysleft3.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        daysleft3.setForeground(new java.awt.Color(52, 170, 231));
        daysleft3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daysleft3.setText("O days left");
        daysleft3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)), new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true)));
        daysleft3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daysleft3MouseEntered(evt);
            }
        });
        jPanel5.add(daysleft3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 120, 40));

        jLabel6.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 170, 231));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Event 4");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 640, 40));

        jPanel7.setBackground(new java.awt.Color(222, 227, 249));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ed5.setBackground(new java.awt.Color(222, 227, 249));
        ed5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        ed5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound18.setText("Edit");
        rSButtonRound18.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        ed5.add(rSButtonRound18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 20));

        rSButtonRound19.setText("Delete");
        rSButtonRound19.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound19ActionPerformed(evt);
            }
        });
        ed5.add(rSButtonRound19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 20));

        rSButtonRound20.setText("Done");
        rSButtonRound20.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound20ActionPerformed(evt);
            }
        });
        ed5.add(rSButtonRound20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jPanel7.add(ed5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 40));

        daysleft4.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        daysleft4.setForeground(new java.awt.Color(52, 170, 231));
        daysleft4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daysleft4.setText("O days left");
        daysleft4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)), new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true)));
        daysleft4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daysleft4MouseEntered(evt);
            }
        });
        jPanel7.add(daysleft4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 120, 40));

        jLabel9.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(52, 170, 231));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Event 5");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 40));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 640, 40));

        jPanel2.setBackground(new java.awt.Color(222, 227, 249));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ed3.setBackground(new java.awt.Color(222, 227, 249));
        ed3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        ed3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound31.setText("Edit");
        rSButtonRound31.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        ed3.add(rSButtonRound31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 20));

        rSButtonRound32.setText("Delete");
        rSButtonRound32.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound32ActionPerformed(evt);
            }
        });
        ed3.add(rSButtonRound32, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 20));

        rSButtonRound33.setText("Done");
        rSButtonRound33.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound33ActionPerformed(evt);
            }
        });
        ed3.add(rSButtonRound33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jPanel2.add(ed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 40));

        daysleft2.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        daysleft2.setForeground(new java.awt.Color(52, 170, 231));
        daysleft2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daysleft2.setText("O days left");
        daysleft2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)), new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true)));
        daysleft2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daysleft2MouseEntered(evt);
            }
        });
        jPanel2.add(daysleft2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 120, 40));

        jLabel5.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 170, 231));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Event 3");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 640, 40));

        jPanel4.setBackground(new java.awt.Color(222, 227, 249));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ed2.setBackground(new java.awt.Color(222, 227, 249));
        ed2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(111, 196, 248), new java.awt.Color(61, 69, 242)));
        ed2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound25.setText("Edit");
        rSButtonRound25.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        ed2.add(rSButtonRound25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 20));

        rSButtonRound26.setText("Delete");
        rSButtonRound26.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound26ActionPerformed(evt);
            }
        });
        ed2.add(rSButtonRound26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 20));

        rSButtonRound27.setText("Done");
        rSButtonRound27.setFont(new java.awt.Font("Roboto Bold", 0, 11)); // NOI18N
        rSButtonRound27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound27ActionPerformed(evt);
            }
        });
        ed2.add(rSButtonRound27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jPanel4.add(ed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 240, 40));

        daysleft1.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        daysleft1.setForeground(new java.awt.Color(52, 170, 231));
        daysleft1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daysleft1.setText("O days left");
        daysleft1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)), new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true)));
        daysleft1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                daysleft1MouseEntered(evt);
            }
        });
        jPanel4.add(daysleft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 120, 40));

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 170, 231));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Event 2");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 640, 40));

        rSButtonRound17.setText("Previous");
        rSButtonRound17.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        rSButtonRound17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound17ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 110, 20));

        rSButtonRound21.setText("Next");
        rSButtonRound21.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        rSButtonRound21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound21ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 90, 20));

        jLabel4.setForeground(new java.awt.Color(52, 170, 231));
        jLabel4.setText("Beta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 0, 50, 40));

        jLabel2.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 144, 250));
        jLabel2.setText("Events");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 90, 50));

        jLabel7.setForeground(new java.awt.Color(62, 1, 1));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-390, 30, 1100, -1));

        rSButtonRound4.setText("New Event");
        rSButtonRound4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound1ActionPerformed
        File f=new File("user.txt");
        f.delete();
        TrayIco t = new TrayIco();
        t.mes="Logged Out";
        try {
            t.main();
        } catch (AWTException ex) {
            Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        Login.main();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound1ActionPerformed

    private void rSButtonRound7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound7ActionPerformed
        Contact.main();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound7ActionPerformed

    private void rSButtonRound6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound6ActionPerformed
        Dash.main();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound6ActionPerformed

    private void rSButtonRound17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound17ActionPerformed

    private void rSButtonRound20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound20ActionPerformed

    private void rSButtonRound21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound21ActionPerformed

    private void rSButtonRound19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound19ActionPerformed

    private void rSButtonRound23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound23ActionPerformed

    private void rSButtonRound24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound24ActionPerformed

    private void rSButtonRound26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound26ActionPerformed

    private void rSButtonRound27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound27ActionPerformed

    private void rSButtonRound29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound29ActionPerformed

    private void rSButtonRound30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound30ActionPerformed

    private void rSButtonRound32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound32ActionPerformed

    private void rSButtonRound33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound33ActionPerformed

    private void e1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1MouseEntered
showedit(1);        // TODO add your handling code here:
    }//GEN-LAST:event_e1MouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
showedit(2);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
showedit(3);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
showedit(4);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
showedit(5);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
hideedit();        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void rSButtonRound4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound4ActionPerformed
        EventEdit.title="New Event";
        EventEdit.task="Add";
        EventEdit.main();
    }//GEN-LAST:event_rSButtonRound4ActionPerformed

    private void rSButtonRound22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound22ActionPerformed
        EventEdit.title="Edit Event";
        EventEdit.task="Edit";
        EventEdit.main();         // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound22ActionPerformed

    private void daysleftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daysleftMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_daysleftMouseEntered

    private void daysleft1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daysleft1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_daysleft1MouseEntered

    private void daysleft2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daysleft2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_daysleft2MouseEntered

    private void daysleft3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daysleft3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_daysleft3MouseEntered

    private void daysleft4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daysleft4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_daysleft4MouseEntered

    private void rSButtonRound3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound3ActionPerformed
        Events.main();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound3ActionPerformed

    /**
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Events().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daysleft;
    private javax.swing.JLabel daysleft1;
    private javax.swing.JLabel daysleft2;
    private javax.swing.JLabel daysleft3;
    private javax.swing.JLabel daysleft4;
    private javax.swing.JLabel e1;
    private javax.swing.JPanel ed1;
    private javax.swing.JPanel ed2;
    private javax.swing.JPanel ed3;
    private javax.swing.JPanel ed4;
    private javax.swing.JPanel ed5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel name;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound1;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound17;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound18;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound19;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound20;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound21;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound22;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound23;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound24;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound25;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound26;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound27;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound28;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound29;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound3;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound30;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound31;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound32;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound33;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound4;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound6;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound7;
    // End of variables declaration//GEN-END:variables
}
