/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sijan
 */
public class EventEdit extends javax.swing.JFrame {

    /**
     * Creates new form NoteEdit
     */
    public EventEdit() {
        initComponents();this.setIconImage(new ImageIcon(getClass().getResource("/icons/icon.png")).getImage());
        this.setTitle(title);
        tt1.setText(task);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tt1 = new javax.swing.JLabel();
        eventt = new RSMaterialComponent.RSTextFieldMaterial();
        eventd = new RSMaterialComponent.RSTextFieldMaterial();
        date = new rojeru_san.rsdate.RSDateChooser();
        rSButtonRoundRipple1 = new rojeru_san.rsbutton.RSButtonRoundRipple();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tt1.setForeground(new java.awt.Color(0, 153, 255));
        tt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tt1.setText("Task");

        eventt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eventt.setPlaceholder("Event Title");
        eventt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventtActionPerformed(evt);
            }
        });

        eventd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eventd.setPlaceholder("Event Details");
        eventd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventdActionPerformed(evt);
            }
        });

        date.setLanguage(rojeru_san.rsdate.RSDateChooser.Language.ENGLISH);
        date.setPlaceholder("Choose Date");

        rSButtonRoundRipple1.setText("Submit");
        rSButtonRoundRipple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRoundRipple1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSButtonRoundRipple1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 10, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eventt, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(eventd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tt1)
                .addGap(17, 17, 17)
                .addComponent(eventt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(eventd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonRoundRipple1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eventtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventtActionPerformed

    private void eventdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventdActionPerformed

    private void rSButtonRoundRipple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRoundRipple1ActionPerformed
        if(eventt.getText().equals("")||eventd.getText().equals("")){
            Toaster t=new Toaster(jPanel1);
            t.error("Please enter all Details X");
        }
        if (task.equals("Edit")) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection sqlConn = new SqlConnection().con;
                PreparedStatement pst = sqlConn.prepareStatement("update events set Event_name = ?, Event_details =?,date=? where UID =?");

                pst.setString(1, eventt.getText());
                pst.setString(2, eventd.getText());
                pst.setString(3, date.getDatoFecha().getYear() + 1900 + "/" + (date.getDatoFecha().getMonth() + 1) + "/" + date.getDatoFecha().getDate());
                pst.setInt(4, new UserDB().getUserID());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated");
                // subject.setText("");
                //note.setText("");
            } catch (ClassNotFoundException | SQLException ex) {

                System.err.println(ex);
            } catch (Exception ex) {
                Logger.getLogger(Note.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(task.equals("Add")){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection sqlConn = new SqlConnection().con;
                PreparedStatement pst = sqlConn.prepareStatement("INSERT INTO `events` (`UID`, `Event_name`, `Event_details`, `date`) VALUES (?,?,?,?)");
                pst.setInt(1, new UserDB().getUserID());
                pst.setString(2, eventt.getText());
                pst.setString(3, eventd.getText());
                pst.setString(4, date.getDatoFecha().getYear() + 1900 + "/" + (date.getDatoFecha().getMonth() + 1) + "/" + date.getDatoFecha().getDate());
                

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Added");
                dispose();
            } catch (ClassNotFoundException | SQLException ex) {

                System.err.println(ex);
            } catch (Exception ex) {
                Logger.getLogger(Note.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRoundRipple1ActionPerformed

    /**
     */
    static String title, task;

    public static boolean main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EventEdit().setVisible(true);
        });
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsdate.RSDateChooser date;
    private RSMaterialComponent.RSTextFieldMaterial eventd;
    private RSMaterialComponent.RSTextFieldMaterial eventt;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.rsbutton.RSButtonRoundRipple rSButtonRoundRipple1;
    private javax.swing.JLabel tt1;
    // End of variables declaration//GEN-END:variables
}
