/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author prabinkokali
 */
public final class Passwords extends javax.swing.JFrame {
    PreparedStatement pst = null;
    ResultSet rs = null;
    int id;
    int[] shid = new int[2000];
    int cid[] = new int[5];
    int rcount = 0;
    
    /**
     * Creates new form Passwords
     */
    public Passwords() {
        
        initComponents();
        prev.setVisible(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/icon.png")).getImage());
         name.setText(getUserData.fname + " " + getUserData.lname);
          avatar.setImage(new ImageIcon(Getuserpic.image));
        isv[1]=true;isv[2]=true;isv[3]=true;isv[4]=true;
        
        id = UserDB.getUserID();
        FetchDBs();

    }
void resetpn(){
    ps1.setVisible(false);ps2.setVisible(false);ps3.setVisible(false);ps4.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roboto1 = new rojeru_san.efectos.Roboto();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        rSButtonRound7 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound6 = new rojeru_san.rsbutton.RSButtonRound();
        jLabel1 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        eye1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        ps1i = new javax.swing.JLabel();
        ps1 = new javax.swing.JLabel();
        sel1 = new rojerusan.RSRadioButton();
        p4 = new javax.swing.JPanel();
        sel4 = new rojerusan.RSRadioButton();
        eye4 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ps4 = new javax.swing.JLabel();
        ps4i = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        sel2 = new rojerusan.RSRadioButton();
        eye2 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ps2 = new javax.swing.JLabel();
        ps2i = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add = new rojeru_san.rsbutton.RSButtonRound();
        no = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        sel3 = new rojerusan.RSRadioButton();
        eye3 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ps3 = new javax.swing.JLabel();
        ps3i = new javax.swing.JLabel();
        prev = new rojeru_san.rsbutton.RSButtonRound();
        next = new rojeru_san.rsbutton.RSButtonRound();
        update = new rojeru_san.rsbutton.RSButtonRound();
        passt = new RSMaterialComponent.RSTextFieldMaterial();
        sitet = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonRound5 = new rojeru_san.rsbutton.RSButtonRound();
        delete = new rojeru_san.rsbutton.RSButtonRound();
        avatar = new home.ImageAvatar();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound7.setText("Contact Us");
        rSButtonRound7.setBorderPainted(false);
        rSButtonRound7.setFocusable(false);
        rSButtonRound7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound7ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 110, 30));

        rSButtonRound6.setText("Back");
        rSButtonRound6.setBorderPainted(false);
        rSButtonRound6.setFocusable(false);
        rSButtonRound6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lifely.png"))); // NOI18N
        jLabel1.setText("Version 1.0");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 50));

        p1.setBackground(new java.awt.Color(254, 254, 254));
        p1.setForeground(new java.awt.Color(62, 157, 254));
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p1MouseEntered(evt);
            }
        });
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eye1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eye1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eyeoff.png"))); // NOI18N
        eye1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye1MouseClicked(evt);
            }
        });
        p1.add(eye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 50, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/passi.png"))); // NOI18N
        p1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, -1, 50));

        jLabel3.setForeground(new java.awt.Color(62, 1, 1));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        p1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, 30, 1060, 20));

        s1.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        s1.setForeground(new java.awt.Color(39, 144, 250));
        p1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 320, 40));

        ps1i.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        ps1i.setForeground(new java.awt.Color(39, 144, 250));
        ps1i.setText("*********************************");
        p1.add(ps1i, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 170, 40));

        ps1.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        ps1.setForeground(new java.awt.Color(39, 144, 250));
        p1.add(ps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 240, 40));

        sel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel1ActionPerformed(evt);
            }
        });
        p1.add(sel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 30, 50));

        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 700, 60));

        p4.setBackground(new java.awt.Color(254, 254, 254));
        p4.setForeground(new java.awt.Color(62, 157, 254));
        p4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p4MouseEntered(evt);
            }
        });
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel4ActionPerformed(evt);
            }
        });
        p4.add(sel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 50));

        eye4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eye4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eyeoff.png"))); // NOI18N
        eye4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye4MouseClicked(evt);
            }
        });
        p4.add(eye4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 50, 50));

        s4.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        s4.setForeground(new java.awt.Color(39, 144, 250));
        p4.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 320, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/passi.png"))); // NOI18N
        p4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jLabel9.setForeground(new java.awt.Color(62, 1, 1));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        p4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-430, 30, 1140, -1));

        ps4.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        ps4.setForeground(new java.awt.Color(39, 144, 250));
        p4.add(ps4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 160, 40));

        ps4i.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        ps4i.setForeground(new java.awt.Color(39, 144, 250));
        ps4i.setText("*********************************");
        p4.add(ps4i, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 230, 40));

        jPanel1.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 700, 60));

        p2.setBackground(new java.awt.Color(254, 254, 254));
        p2.setForeground(new java.awt.Color(62, 157, 254));
        p2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p2MouseEntered(evt);
            }
        });
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel2ActionPerformed(evt);
            }
        });
        p2.add(sel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 50));

        eye2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eye2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eyeoff.png"))); // NOI18N
        eye2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye2MouseClicked(evt);
            }
        });
        p2.add(eye2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 50, 50));

        s2.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        s2.setForeground(new java.awt.Color(39, 144, 250));
        p2.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 320, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/passi.png"))); // NOI18N
        p2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        jLabel14.setForeground(new java.awt.Color(62, 1, 1));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        p2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 30, 1110, -1));

        ps2.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        ps2.setForeground(new java.awt.Color(39, 144, 250));
        p2.add(ps2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 170, 40));

        ps2i.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        ps2i.setForeground(new java.awt.Color(39, 144, 250));
        ps2i.setText("*********************************");
        p2.add(ps2i, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 240, 40));

        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 700, 60));

        jLabel5.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(39, 144, 250));
        jLabel5.setText("Password Manager");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 190, 50));

        add.setText("Add Password");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 130, 30));

        no.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        no.setForeground(new java.awt.Color(39, 144, 250));
        no.setText("0 Sites And Apps");
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 140, 50));

        p3.setBackground(new java.awt.Color(254, 254, 254));
        p3.setForeground(new java.awt.Color(62, 157, 254));
        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p3MouseEntered(evt);
            }
        });
        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel3ActionPerformed(evt);
            }
        });
        p3.add(sel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 50));

        eye3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eye3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eyeoff.png"))); // NOI18N
        eye3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye3MouseClicked(evt);
            }
        });
        p3.add(eye3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 50, 50));

        s3.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        s3.setForeground(new java.awt.Color(39, 144, 250));
        p3.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 320, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/passi.png"))); // NOI18N
        p3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jLabel20.setForeground(new java.awt.Color(62, 1, 1));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        p3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-430, 30, 1140, -1));

        ps3.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        ps3.setForeground(new java.awt.Color(39, 144, 250));
        p3.add(ps3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 170, 40));

        ps3i.setFont(new java.awt.Font("Roboto Slab", 1, 12)); // NOI18N
        ps3i.setForeground(new java.awt.Color(39, 144, 250));
        ps3i.setText("*********************************");
        p3.add(ps3i, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 230, 40));

        jPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 700, 60));

        prev.setText("Previous");
        prev.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });
        jPanel1.add(prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 110, 30));

        next.setText("Next");
        next.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 90, 30));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 100, 30));

        passt.setPlaceholder("Password");
        passt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtActionPerformed(evt);
            }
        });
        jPanel1.add(passt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 40));

        sitet.setPlaceholder("Site");
        sitet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitetActionPerformed(evt);
            }
        });
        jPanel1.add(sitet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 40));

        rSButtonRound5.setText("Refresh");
        rSButtonRound5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound5ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 90, 30));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, 30));

        avatar.setImage(new javax.swing.ImageIcon(getClass().getResource("/icons/usrimg.PNG"))); // NOI18N
        avatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avatarMouseClicked(evt);
            }
        });
        jPanel1.add(avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 40, 40));

        jLabel6.setForeground(new java.awt.Color(62, 1, 1));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, 40, 1320, -1));

        name.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(29, 161, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name.setText("Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 280, 40));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    String[] pass = new String[2000];

    String[] site = new String[2000];
    int i = 0,pi=0;

    void FetchDBs() {
        resetpn();
        try {
            PreparedStatement pss;
            String queryString = "SELECT * FROM passwords Where UID=" + getUserData.ID;
            pss = DB.getConnection().prepareStatement(queryString);
            try (ResultSet results = pss.executeQuery()) {
                while (results.next()) {

                    pass[pi] = results.getString("password");
                    site[pi] = results.getString("SiteName");
                    shid[pi] = results.getInt("ID");
                    pi++;

                }

            }
            no.setText(pi + "Sites And Apps");
            if (pi >= 1) {
                p1.setVisible(true);
                ps1.setText(pass[rcount]);
                s1.setText(site[rcount]);
                cid[1] = shid[rcount];

            }
            if (pi >= 2) {
                p2.setVisible(true);
                ps2.setText(pass[rcount+1]);
                s2.setText(site[rcount+1]);
                cid[2] = shid[rcount+1];

            }
            if (pi >= 3) {
                p3.setVisible(true);
                ps3.setText(pass[rcount+2]);
                s3.setText(site[rcount+2]);
                cid[3] = shid[rcount+2];

            }
            if (pi >= 4) {
                p4.setVisible(true);
                ps4.setText(pass[rcount+3]);
                s4.setText(site[rcount+3]);
                cid[4] = shid[rcount+3];

            }
            
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }
    private void rSButtonRound6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound6ActionPerformed
        Dash.main();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound6ActionPerformed
int seid=0;
    private void rSButtonRound7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound7ActionPerformed
        Contact.main();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound7ActionPerformed

    int validates(){
    if(passt.getText().equals("")||sitet.getText().equals("")){
        Toaster t=new Toaster(jPanel1);
        t.error("Please Fill all Details");
        return 1;
    }else{
        return 0;
    }
}
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
rcount=0;        if(validates()==0)  {      try {
            Statement stmt = DB.getConnection().createStatement();
            stmt.execute("INSERT INTO `passwords`(`UID`, `SiteName`, `Password`) VALUES (" + UserDB.getUserID() + ",'" + sitet.getText() + "','" + passt.getText() + "')");
           pi=0;
           FetchDBs();
           sitet.setText("");
           passt.setText("");
        } catch (SQLException ex) {
            System.err.println(ex);
        }}
    }//GEN-LAST:event_addActionPerformed
    void AddPass() {

    }

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        if(rcount<=3){
        rcount=0;
        prev.setVisible(true);}
        
        
        else{
            rcount=rcount-4;}
                
                System.out.println(rcount+" "+pi);
                ps1.setText(pass[rcount+1]);
                s1.setText(site[rcount+1]);
                cid[1] = shid[rcount+1];
               
                ps2.setText(pass[rcount+2]);
                s2.setText(site[rcount+2]);
                cid[2] = shid[rcount+2];
               
                ps3.setText(pass[rcount+3]);
                s3.setText(site[rcount+3]);
                cid[3] = shid[rcount+3];
              
                ps4.setText(pass[rcount+4]);
                s4.setText(site[rcount+4]);
                cid[4] = shid[rcount+4];
                
                    next.setVisible(true);
                
    }//GEN-LAST:event_prevActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if(rcount<3){
        rcount=rcount+3;
        prev.setVisible(true);}
        
        else{
            rcount=rcount+4;}
                p1.setVisible(true);
                System.out.println(rcount+" "+pi);
                ps1.setText(pass[rcount+1]);
                s1.setText(site[rcount+1]);
                cid[1] = shid[rcount+1];
                p2.setVisible(true);
                ps2.setText(pass[rcount+2]);
                s2.setText(site[rcount+2]);
                cid[2] = shid[rcount+2];
                p3.setVisible(true);
                ps3.setText(pass[rcount+3]);
                s3.setText(site[rcount+3]);
                cid[3] = shid[rcount+3];
                p4.setVisible(true);
                ps4.setText(pass[rcount+4]);
                s4.setText(site[rcount+4]);
                cid[4] = shid[rcount+4];
                
                if(rcount>pi){
                    next.setVisible(false);
                }
    }//GEN-LAST:event_nextActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
rcount=0;if(validates()==0)  {        try {
            Statement stmt = DB.getConnection().createStatement();
            //stmt.execute("INSERT INTO `passwords`(`UID`, `SiteName`, `Password`) VALUES (" + UserDB.getUserID() + ",'" + sitet.getText() + "','" + passt.getText() + "')");
            stmt.execute("UPDATE `passwords` SET `SiteName`='" + sitet.getText() + "',`Password`='" + passt.getText() + "' WHERE ID="+seid);
           // JOptionPane.showMessageDialog(this, "Password Added");
           pi=0;
           
           FetchDBs();
           sitet.setText("");
           passt.setText("");
           //Passwords.main();
        } catch (SQLException ex) {
            System.err.println(ex);
        }}
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void sel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel2ActionPerformed
        selectpass(2);  // TODO add your handling code here:
    }//GEN-LAST:event_sel2ActionPerformed

    private void sel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel3ActionPerformed
        selectpass(3);  // TODO add your handling code here:
    }//GEN-LAST:event_sel3ActionPerformed

    private void sel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel4ActionPerformed
        selectpass(4);   // TODO add your handling code here:
    }//GEN-LAST:event_sel4ActionPerformed

    private void sel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel1ActionPerformed
        selectpass(1);
        sitet.setText(s1.getText());
        passt.setText(ps1.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_sel1ActionPerformed
    void selectpass(int num) {
        switch (num) {
            case 1:
                removeSelection();
                sel1.setSelected(true);
                seid=cid[1];
                break;
            case 2:
                removeSelection();
                sel2.setSelected(true);
                seid=cid[2];
                break;
            case 3:
                removeSelection();
                sel3.setSelected(true);
                seid=cid[3];
                break;
            case 4:
                removeSelection();
                sel4.setSelected(true);
                seid=cid[4];
                break;
            default:
                removeSelection();

        }

    }

    void removeSelection() {
        sel1.setSelected(false);
        sel2.setSelected(false);
        sel3.setSelected(false);
        sel4.setSelected(false);
    }
    private void p1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseEntered
        
    }//GEN-LAST:event_p1MouseEntered

    private void p2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p2MouseEntered

    private void p3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseEntered
      // TODO add your handling code here:
    }//GEN-LAST:event_p3MouseEntered

    private void p4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseEntered
      // TODO add your handling code here:
    }//GEN-LAST:event_p4MouseEntered

    void passinvisible(int n) {
        ImageIcon image = new ImageIcon(getClass().getResource("/icons/eyeon.png"));
        ImageIcon image1 = new ImageIcon(getClass().getResource("/icons/eyeoff.png"));
        switch (n) {
            case 1:
                passinvisible(0);
                ps1i.setVisible(false);
                ps1.setVisible(true);
                eye1.setIcon(image);
                
                break;
            case 2:
                 passinvisible(0);
                 ps2i.setVisible(false);
                ps2.setVisible(true);
                eye2.setIcon(image);
               
                break;
            case 3:
                 passinvisible(0);
                 ps3i.setVisible(false);
                ps3.setVisible(true);
                eye3.setIcon(image);
               
                break;
            case 4:
                passinvisible(0);
                ps4i.setVisible(false);
                ps4.setVisible(true);
                eye4.setIcon(image);
                
                break;
            default:
                ps1i.setVisible(true);
                ps1.setVisible(false);
                ps2i.setVisible(true);
                ps2.setVisible(false);
                ps3i.setVisible(true);
                ps3.setVisible(false);
                ps4i.setVisible(true);
                ps4.setVisible(false);
                eye1.setIcon(image1);
                eye2.setIcon(image1);
                eye3.setIcon(image1);
                eye4.setIcon(image1);
                break;
        }
    }
    private void eye1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye1MouseClicked
        if(isv[1]){
        passinvisible(1);
        isv[1]=false;
        }
        else{
            isv[1]=true;
            passinvisible(0);
        }

    }//GEN-LAST:event_eye1MouseClicked
    boolean[] isv=new boolean[5];
    
    private void passtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtActionPerformed

    private void sitetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitetActionPerformed

    private void rSButtonRound5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound5ActionPerformed
        Passwords.main();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound5ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
rcount=0;if(validates()==0)  {        int deleteItem = JOptionPane.showConfirmDialog(null, "Confirm if you want to delete item",
                    "Warning", JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION) {

     try {
         pst = DB.getConnection().prepareStatement("delete from passwords where id ="+seid);
         pst.executeUpdate();
         pi=0;
           FetchDBs();
           sitet.setText("");
           passt.setText("");
     } // TODO add your handling code here:
     catch (SQLException ex) {
         Logger.getLogger(Passwords.class.getName()).log(Level.SEVERE, null, ex);
     }
            }
            }
    }//GEN-LAST:event_deleteActionPerformed

    private void eye2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye2MouseClicked
if(isv[2]){
        passinvisible(2);
        isv[2]=false;
        }
        else{
            isv[2]=true;
            passinvisible(0);
        }
    }//GEN-LAST:event_eye2MouseClicked

    private void eye3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye3MouseClicked
if(isv[3]){
        passinvisible(3);
        isv[3]=false;
        }
        else{
            isv[3]=true;
            passinvisible(0);
        }
    }//GEN-LAST:event_eye3MouseClicked

    private void eye4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye4MouseClicked
if(isv[4]){
        passinvisible(4);
        isv[4]=false;
        }
        else{
            isv[4]=true;
            passinvisible(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_eye4MouseClicked

    private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked

selectpass(1);
        sitet.setText(s1.getText());
        passt.setText(ps1.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_p1MouseClicked

    private void p2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseClicked
selectpass(2);
        sitet.setText(s2.getText());
        passt.setText(ps2.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_p2MouseClicked

    private void p3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MouseClicked
  selectpass(3);
        sitet.setText(s3.getText());
        passt.setText(ps3.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_p3MouseClicked

    private void p4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p4MouseClicked
  selectpass(4);
        sitet.setText(s4.getText());
        passt.setText(ps4.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_p4MouseClicked

    private void avatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avatarMouseClicked
        Userprofile.main();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_avatarMouseClicked

    /**
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passwords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Passwords().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsbutton.RSButtonRound add;
    private home.ImageAvatar avatar;
    private rojeru_san.rsbutton.RSButtonRound delete;
    private javax.swing.JLabel eye1;
    private javax.swing.JLabel eye2;
    private javax.swing.JLabel eye3;
    private javax.swing.JLabel eye4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private rojeru_san.rsbutton.RSButtonRound next;
    private javax.swing.JLabel no;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private RSMaterialComponent.RSTextFieldMaterial passt;
    private rojeru_san.rsbutton.RSButtonRound prev;
    private javax.swing.JLabel ps1;
    private javax.swing.JLabel ps1i;
    private javax.swing.JLabel ps2;
    private javax.swing.JLabel ps2i;
    private javax.swing.JLabel ps3;
    private javax.swing.JLabel ps3i;
    private javax.swing.JLabel ps4;
    private javax.swing.JLabel ps4i;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound5;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound6;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound7;
    private rojeru_san.efectos.Roboto roboto1;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private rojerusan.RSRadioButton sel1;
    private rojerusan.RSRadioButton sel2;
    private rojerusan.RSRadioButton sel3;
    private rojerusan.RSRadioButton sel4;
    private RSMaterialComponent.RSTextFieldMaterial sitet;
    private rojeru_san.rsbutton.RSButtonRound update;
    // End of variables declaration//GEN-END:variables
}
