/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.awt.AWTException;
import java.io.File;
import static java.lang.Thread.sleep;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sijan
 */
public class PSchange extends javax.swing.JFrame {

    /**
     * Creates new form PSchange
     */
    public PSchange() {
        t = new Toaster(jPanel1);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        np = new RSMaterialComponent.RSTextFieldIconUno();
        cp = new RSMaterialComponent.RSTextFieldIconUno();
        submit = new rojeru_san.rsbutton.RSButtonRoundEffect();
        rSButtonRound9 = new rojeru_san.rsbutton.RSButtonRound();
        jLabel3 = new javax.swing.JLabel();
        p = new RSMaterialComponent.RSTextFieldIconUno();
        rSButtonRoundEffect1 = new rojeru_san.rsbutton.RSButtonRoundEffect();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change password");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lifely.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        title.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(29, 161, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title.setText("Change Password");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 240, 50));

        np.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCK);
        np.setPlaceholder("Current Password");
        jPanel1.add(np, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, 40));

        cp.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCK);
        cp.setPlaceholder("Confirm Password");
        jPanel1.add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        submit.setBackground(new java.awt.Color(255, 102, 153));
        submit.setText("Change Password");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 160, -1));

        rSButtonRound9.setText("Back");
        rSButtonRound9.setBorderPainted(false);
        rSButtonRound9.setFocusable(false);
        rSButtonRound9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound9ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 70, 30));

        jLabel3.setForeground(new java.awt.Color(62, 1, 1));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-670, 30, 1150, -1));

        p.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCK);
        p.setPlaceholder("New Password");
        jPanel1.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        rSButtonRoundEffect1.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonRoundEffect1.setText("Log Out");
        rSButtonRoundEffect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRoundEffect1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRoundEffect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
Toaster t;
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if (p.getText().equals(cp.getText())) {
            if (Crypt.passcrypt(np.getText()).equals(getUserData.pass)) {
                JOptionPane.showMessageDialog(this, "Password Updated");
                

            } else {
                t.error("Incorrect password");
            }

        } else {
            t.error("Please Confirm Password Correctly");
            cp.setText("");

        }
    }//GEN-LAST:event_submitActionPerformed


    private void rSButtonRound9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound9ActionPerformed

        Userprofile.main();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound9ActionPerformed

    private void rSButtonRoundEffect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRoundEffect1ActionPerformed
        File f = new File("user.txt");

        if (f.exists()) {

            f.delete();
        }
        File ff=new File("user.png");
        if(ff.exists()){
            ff.delete();
        }
        TrayIco tr = new TrayIco();
        TrayIco.mes = "Logged Out";
        try {
            TrayIco.main();
        } catch (AWTException ex) {
            Logger.getLogger(Userprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
        Login.main();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRoundEffect1ActionPerformed

    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PSchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PSchange().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSTextFieldIconUno cp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSTextFieldIconUno np;
    private RSMaterialComponent.RSTextFieldIconUno p;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound9;
    private rojeru_san.rsbutton.RSButtonRoundEffect rSButtonRoundEffect1;
    private rojeru_san.rsbutton.RSButtonRoundEffect submit;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
