/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.awt.AWTException;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sijan
 */
public final class Userprofile extends javax.swing.JFrame {

    String fname, lname, email;

    /**
     * Creates new form Userprofile
     */
    public Userprofile() {
        initComponents();
        EditMode(false);
        
        try (BufferedReader bw = new BufferedReader(new FileReader(new File("user.txt")))) {
            bw.readLine();
            fname = Crypt.decrypt(bw.readLine());
            lname = Crypt.decrypt(bw.readLine());
            ff.setText(fname);
            ll.setText(lname);
            email = Crypt.decrypt(bw.readLine());
            ee.setText(email);
            bw.close();
            //name.setText(home.Crypt.decrypt(bw.readLine()) + " " + home.Crypt.decrypt(bw.readLine()));
        } catch (Exception ex) {
            Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSButtonRound7 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound8 = new rojeru_san.rsbutton.RSButtonRound();
        rSButtonRound9 = new rojeru_san.rsbutton.RSButtonRound();
        usri = new rojeru_san.rslabel.RSLabelBorderRound();
        ee = new RSMaterialComponent.RSTextFieldIconUno();
        ll = new RSMaterialComponent.RSTextFieldIconUno();
        rSButtonRoundEffect1 = new rojeru_san.rsbutton.RSButtonRoundEffect();
        up1 = new rojeru_san.rsbutton.RSButtonRoundEffect();
        title = new javax.swing.JLabel();
        ff = new RSMaterialComponent.RSTextFieldIconUno();
        up2 = new rojeru_san.rsbutton.RSButtonRoundEffect();
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edt = new rojerusan.RSCheckBox();
        jLabel3 = new javax.swing.JLabel();
        up4 = new rojeru_san.rsbutton.RSButtonRoundEffect();
        up3 = new rojeru_san.rsbutton.RSButtonRoundEffect();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonRound7.setText("Contact Us");
        rSButtonRound7.setBorderPainted(false);
        rSButtonRound7.setFocusable(false);
        rSButtonRound7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound7ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 110, 30));

        rSButtonRound8.setText("About Us");
        rSButtonRound8.setBorderPainted(false);
        rSButtonRound8.setFocusable(false);
        rSButtonRound8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound8ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 90, 30));

        rSButtonRound9.setText("Back");
        rSButtonRound9.setBorderPainted(false);
        rSButtonRound9.setFocusable(false);
        rSButtonRound9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound9ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 70, 30));

        usri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usri.setText("Click to Change");
        usri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usriMouseClicked(evt);
            }
        });
        jPanel1.add(usri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, 190));

        ee.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EMAIL);
        ee.setPlaceholder("Email");
        jPanel1.add(ee, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        ll.setPlaceholder("Last Name");
        jPanel1.add(ll, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        rSButtonRoundEffect1.setText("Log Out");
        rSButtonRoundEffect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRoundEffect1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRoundEffect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 110, -1));

        up1.setText("Update");
        up1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up1ActionPerformed(evt);
            }
        });
        jPanel1.add(up1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 110, -1));

        title.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(29, 161, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title.setText("Profile");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 60, 50));

        ff.setPlaceholder("First Name");
        jPanel1.add(ff, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        up2.setText("Update");
        up2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up2ActionPerformed(evt);
            }
        });
        jPanel1.add(up2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 110, -1));

        name.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(29, 161, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name.setText("Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 60, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lifely.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        edt.setText("Edit Profile");
        edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtActionPerformed(evt);
            }
        });
        jPanel1.add(edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 130, 30));

        jLabel3.setForeground(new java.awt.Color(62, 1, 1));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 590, -1));

        up4.setText("Upload");
        up4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up4ActionPerformed(evt);
            }
        });
        jPanel1.add(up4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 110, -1));

        up3.setText("Update");
        up3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up3ActionPerformed(evt);
            }
        });
        jPanel1.add(up3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
void fetchData() {

    }
    private void rSButtonRound7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound7ActionPerformed
        Contact.main();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound7ActionPerformed

    private void rSButtonRound8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound8ActionPerformed
        About.main();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound8ActionPerformed

    private void rSButtonRound9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound9ActionPerformed

        Dash.main();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound9ActionPerformed
    File usrimg;
    private void usriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usriMouseClicked
        JFileChooser jf = new JFileChooser();
        usrimg = jf.getSelectedFile();
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF Images", "jpg", "gif");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: "
                    + chooser.getSelectedFile().getName());
            usrimg = chooser.getSelectedFile();
            Icon icon = new ImageIcon(usrimg.getPath());
            BufferedImage img = new ImgUtils().scaleImage(190, 190, usrimg.getPath());
            usri.setIcon(new ImageIcon(img));
        }

    }//GEN-LAST:event_usriMouseClicked

    private void rSButtonRoundEffect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRoundEffect1ActionPerformed
        File f = new File("user.txt");
        f.delete();
        TrayIco t = new TrayIco();
        t.mes = "Logged Out";
        try {
            t.main();
        } catch (AWTException ex) {
            Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        Login.main();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRoundEffect1ActionPerformed

    private void up4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up4ActionPerformed
 try {
            String sql = "INSERT INTO users (Image) values (?)";
            PreparedStatement statement = DB.getConnection().prepareStatement(sql);
            InputStream inputStream = new FileInputStream(usrimg);
            statement.setBlob(1, inputStream);
            int row = statement.executeUpdate();
            if (row > 0) {
                System.out.println("Profile Picture Updated");
            }
            System.out.println("uploaded Image");
        } catch (SQLException | FileNotFoundException ex) {
            Logger.getLogger(Contact.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_up4ActionPerformed

    private void up3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up3ActionPerformed
  try {
            Statement stmt = DB.getConnection().createStatement();
            stmt.execute("update users set Email = '" + ee.getText() + "' where id =" + UserDB.getUserID());
        } catch (SQLException ex) {
            Logger.getLogger(Userprofile.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_up3ActionPerformed
    void EditMode(boolean on) {
        if (on) {
            ff.setEditable(true);
            ll.setEditable(false);
            ee.setEditable(true);

            up1.setVisible(true);
            up2.setVisible(true);
            up3.setVisible(true);
            up4.setVisible(true);
            usri.setText("Click to change");
        } else {
            up1.setVisible(false);
            up2.setVisible(false);
            up3.setVisible(false);
            up4.setVisible(false);
            usri.setText("");
        }
    }
    private void edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtActionPerformed
        if (edt.isSelected()) {
            EditMode(true);
        } else {
            EditMode(false);
        }
    }//GEN-LAST:event_edtActionPerformed

    private void up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up1ActionPerformed
        try {
            Statement stmt = DB.getConnection().createStatement();
            stmt.execute("update users set FirstName = '" + ff.getText() + "' where id =" + UserDB.getUserID());
            JOptionPane.showMessageDialog(this, "FirstName Updated");
        } catch (SQLException ex) {
            Logger.getLogger(Userprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_up1ActionPerformed

    private void up2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up2ActionPerformed
        try {
            Statement stmt = DB.getConnection().createStatement();
            stmt.execute("update users set LastName = '" + ll.getText() + "' where id =" + UserDB.getUserID());
        } catch (SQLException ex) {
            Logger.getLogger(Userprofile.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_up2ActionPerformed
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Userprofile().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSCheckBox edt;
    private RSMaterialComponent.RSTextFieldIconUno ee;
    private RSMaterialComponent.RSTextFieldIconUno ff;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSTextFieldIconUno ll;
    private javax.swing.JLabel name;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound7;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound8;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound9;
    private rojeru_san.rsbutton.RSButtonRoundEffect rSButtonRoundEffect1;
    private javax.swing.JLabel title;
    private rojeru_san.rsbutton.RSButtonRoundEffect up1;
    private rojeru_san.rsbutton.RSButtonRoundEffect up2;
    private rojeru_san.rsbutton.RSButtonRoundEffect up3;
    private rojeru_san.rsbutton.RSButtonRoundEffect up4;
    private rojeru_san.rslabel.RSLabelBorderRound usri;
    // End of variables declaration//GEN-END:variables
}
