/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.awt.AWTException;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sijan
 */
public final class Userprofile extends javax.swing.JFrame {

    String fname, lname, email;

    /**
     * Creates new form Userprofile
     */
    public Userprofile() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/icon.png")).getImage());
        EditMode(false);
        ImageIcon im=new ImageIcon(Getuserpic.image);
        avatar.setImage(im);
        usri.setIcon(im);
        getUserData userData = new getUserData();
            fname = getUserData.fname;
            lname = getUserData.lname;
            ff.setText(fname);
            ll.setText(lname);
            email = getUserData.email;
            ee.setText(email);
            name.setText(fname+" "+lname);
            fetchData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        avatar = new home.ImageAvatar();
        rSButtonRound9 = new rojeru_san.rsbutton.RSButtonRound();
        usri = new rojeru_san.rslabel.RSLabelBorderRound();
        ee = new RSMaterialComponent.RSTextFieldIconUno();
        ll = new RSMaterialComponent.RSTextFieldIconUno();
        logout = new rojeru_san.rsbutton.RSButtonRoundEffect();
        up1 = new rojeru_san.rsbutton.RSButtonRoundEffect();
        title = new javax.swing.JLabel();
        ff = new RSMaterialComponent.RSTextFieldIconUno();
        up2 = new rojeru_san.rsbutton.RSButtonRoundEffect();
        name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edt = new rojerusan.RSCheckBox();
        jLabel3 = new javax.swing.JLabel();
        up4 = new rojeru_san.rsbutton.RSButtonRoundEffect();
        up3 = new rojeru_san.rsbutton.RSButtonRoundEffect();
        rSButtonRoundEffect2 = new rojeru_san.rsbutton.RSButtonRoundEffect();
        jLabel4 = new javax.swing.JLabel();
        taskd = new RSMaterialComponent.RSButtonMaterialRipple();
        passd = new RSMaterialComponent.RSButtonMaterialRipple();
        eventd = new RSMaterialComponent.RSButtonMaterialRipple();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        avatar.setImage(new javax.swing.ImageIcon(getClass().getResource("/icons/usrimg.PNG"))); // NOI18N
        avatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avatarMouseClicked(evt);
            }
        });
        jPanel1.add(avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 40, 40));

        rSButtonRound9.setText("Back");
        rSButtonRound9.setBorderPainted(false);
        rSButtonRound9.setFocusPainted(false);
        rSButtonRound9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound9ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 70, 30));

        usri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usri.setText("Click to Change");
        usri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usriMouseClicked(evt);
            }
        });
        jPanel1.add(usri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 190, 190));

        ee.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EMAIL);
        ee.setPlaceholder("Email");
        jPanel1.add(ee, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        ll.setPlaceholder("Last Name");
        jPanel1.add(ll, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        logout.setBackground(new java.awt.Color(0, 153, 153));
        logout.setText("Log Out");
        logout.setFocusPainted(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 110, -1));

        up1.setText("Update");
        up1.setFocusPainted(false);
        up1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up1ActionPerformed(evt);
            }
        });
        jPanel1.add(up1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 110, -1));

        title.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(29, 161, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title.setText("Profile");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 60, 50));

        ff.setPlaceholder("First Name");
        jPanel1.add(ff, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        up2.setText("Update");
        up2.setFocusPainted(false);
        up2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up2ActionPerformed(evt);
            }
        });
        jPanel1.add(up2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 110, -1));

        name.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(29, 161, 255));
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name.setText("Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 280, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lifely.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        edt.setText("Edit Profile");
        edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtActionPerformed(evt);
            }
        });
        jPanel1.add(edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 130, 30));

        jLabel3.setForeground(new java.awt.Color(62, 1, 1));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 140, 990, 30));

        up4.setText("Upload");
        up4.setFocusPainted(false);
        up4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up4ActionPerformed(evt);
            }
        });
        jPanel1.add(up4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 110, -1));

        up3.setText("Update");
        up3.setFocusPainted(false);
        up3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up3ActionPerformed(evt);
            }
        });
        jPanel1.add(up3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 110, -1));

        rSButtonRoundEffect2.setBackground(new java.awt.Color(255, 102, 153));
        rSButtonRoundEffect2.setText("Change Password");
        rSButtonRoundEffect2.setFocusPainted(false);
        rSButtonRoundEffect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRoundEffect2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRoundEffect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 160, -1));

        jLabel4.setForeground(new java.awt.Color(62, 1, 1));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 30, 990, 40));

        taskd.setBackground(new java.awt.Color(102, 102, 255));
        taskd.setText("0 Tasks");
        taskd.setFocusPainted(false);
        taskd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskdActionPerformed(evt);
            }
        });
        jPanel1.add(taskd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 180, 70));

        passd.setBackground(new java.awt.Color(0, 204, 204));
        passd.setText("0 Passwords");
        passd.setFocusPainted(false);
        passd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passdActionPerformed(evt);
            }
        });
        jPanel1.add(passd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 180, 70));

        eventd.setText("0 Events");
        eventd.setFocusPainted(false);
        eventd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventdActionPerformed(evt);
            }
        });
        jPanel1.add(eventd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int noten,eventn,passn;
    void fetchData() {
        try {
            PreparedStatement ps;
            String queryString = "SELECT * from notes Where UserID=" + UserDB.getUserID();
            ps = DB.getConnection().prepareStatement(queryString);
            try (ResultSet results = ps.executeQuery()) {
                while (results.next()) {
                    noten++;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            PreparedStatement ps;
            String queryString = "SELECT * from events Where UID=" + UserDB.getUserID();
            ps = DB.getConnection().prepareStatement(queryString);
            try (ResultSet results = ps.executeQuery()) {
                while (results.next()) {
                    eventn++;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            PreparedStatement ps;
            String queryString = "SELECT * from passwords Where UID=" + UserDB.getUserID();
            ps = DB.getConnection().prepareStatement(queryString);
            try (ResultSet results = ps.executeQuery()) {
                while (results.next()) {
                    passn++;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
        }    
        passd.setText(passn+" Passwords");
        eventd.setText(eventn+" Events");
        taskd.setText(noten+" Tasks");
    }
    private void rSButtonRound9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound9ActionPerformed

        Dash.main();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound9ActionPerformed
    File usrimg;
    private void usriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usriMouseClicked
        JFileChooser jf = new JFileChooser();
        usrimg = jf.getSelectedFile();
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG, PNG & GIF Images", "jpg","png", "gif");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: "
                    + chooser.getSelectedFile().getName());
            usrimg = chooser.getSelectedFile();
            Icon icon = new ImageIcon(usrimg.getPath());
            BufferedImage img = new ImgUtils().scaleImage(190, 190, usrimg.getPath());
            usri.setIcon(new ImageIcon(img));
        }

    }//GEN-LAST:event_usriMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        File f = new File("user.txt");
        File fff=new File("user.png");
        if (f.exists()) {
            f.delete();
        }
        if (fff.exists()) {
            fff.delete();
        }
        getUserData.isset=0;
        Getuserpic.isset=0;
        TrayIco t = new TrayIco();
        TrayIco.mes = "Logged Out";
        try {
            TrayIco.main();
        } catch (AWTException ex) {
            Logger.getLogger(Userprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
        Login.main();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void up4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up4ActionPerformed
        try {
            String sql = "update users set Image = ? where id =" + UserDB.getUserID();
            PreparedStatement statement = DB.getConnection().prepareStatement(sql);
            InputStream inputStream = new FileInputStream(usrimg);
            statement.setBlob(1, inputStream);
            int row = statement.executeUpdate();
            if (row > 0) {
                JOptionPane.showMessageDialog(this, "Profile Picture Updated, Relogin to see changes");
                Getuserpic.isset=0;
                Getuserpic userpic = new Getuserpic();
                Getuserpic.image = ImageIO.read(usrimg);
                    
                    Getuserpic.userimg = new File("user.png");
                    if(Getuserpic.userimg.exists())Getuserpic.userimg.delete();
                    ImageIO.write(Getuserpic.image, "png", Getuserpic.userimg);
                    logout.doClick();
                    dispose();
            }
                    
                    
            System.out.println("uploaded Image");
        } catch (SQLException | FileNotFoundException ex) {
            DB.con=null;
            DB.getConnection();
            Logger.getLogger(Contact.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Userprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_up4ActionPerformed

    private void up3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up3ActionPerformed
        try {
            Statement stmt = DB.getConnection().createStatement();
            stmt.execute("update users set Email = '" + ee.getText() + "' where id =" + UserDB.getUserID());
            JOptionPane.showMessageDialog(this, "Username Updated");
            getUserData.isset=0;
            Userprofile.main();
            dispose();
        } catch (SQLException ex) {DB.con=null;
            DB.getConnection();
            Logger.getLogger(Userprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_up3ActionPerformed
    void EditMode(boolean on) {
        if (on) {
            ff.setEditable(true);
            ll.setEditable(false);
            ee.setEditable(true);

            up1.setVisible(true);
            up2.setVisible(true);
            up3.setVisible(true);
            up4.setVisible(true);
            usri.setText("Click to change");
        } else {
            up1.setVisible(false);
            up2.setVisible(false);
            up3.setVisible(false);
            up4.setVisible(false);
            usri.setText("");
        }
    }
    private void edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtActionPerformed
        if (edt.isSelected()) {
            EditMode(true);
        } else {
            EditMode(false);
        }
    }//GEN-LAST:event_edtActionPerformed

    private void up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up1ActionPerformed
        try {
            Statement stmt = DB.getConnection().createStatement();
            stmt.execute("update users set FirstName = '" + ff.getText() + "' where id =" + UserDB.getUserID());
            JOptionPane.showMessageDialog(this, "FirstName Updated");
            getUserData.isset=0;
            Userprofile.main();
            dispose();
        } catch (SQLException ex) {DB.con=null;
            DB.getConnection();
            Logger.getLogger(Userprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_up1ActionPerformed

    private void up2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up2ActionPerformed
        try {
            Statement stmt = DB.getConnection().createStatement();
            stmt.execute("update users set LastName = '" + ll.getText() + "' where id =" + UserDB.getUserID());
            JOptionPane.showMessageDialog(this, "LastName Updated");
            getUserData.isset=0;
            Userprofile.main();
            dispose();
        } catch (SQLException ex) {DB.con=null;
            DB.getConnection();
            Logger.getLogger(Userprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_up2ActionPerformed

    private void rSButtonRoundEffect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRoundEffect2ActionPerformed
PSchange.main();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRoundEffect2ActionPerformed

    private void avatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avatarMouseClicked
        Userprofile.main();
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_avatarMouseClicked

    private void eventdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventdActionPerformed
Events.main();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_eventdActionPerformed

    private void taskdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskdActionPerformed
Note.main();
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_taskdActionPerformed

    private void passdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passdActionPerformed
Passwords.main();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_passdActionPerformed
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Userprofile().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private home.ImageAvatar avatar;
    private rojerusan.RSCheckBox edt;
    private RSMaterialComponent.RSTextFieldIconUno ee;
    private RSMaterialComponent.RSButtonMaterialRipple eventd;
    private RSMaterialComponent.RSTextFieldIconUno ff;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSTextFieldIconUno ll;
    private rojeru_san.rsbutton.RSButtonRoundEffect logout;
    private javax.swing.JLabel name;
    private RSMaterialComponent.RSButtonMaterialRipple passd;
    private rojeru_san.rsbutton.RSButtonRound rSButtonRound9;
    private rojeru_san.rsbutton.RSButtonRoundEffect rSButtonRoundEffect2;
    private RSMaterialComponent.RSButtonMaterialRipple taskd;
    private javax.swing.JLabel title;
    private rojeru_san.rsbutton.RSButtonRoundEffect up1;
    private rojeru_san.rsbutton.RSButtonRoundEffect up2;
    private rojeru_san.rsbutton.RSButtonRoundEffect up3;
    private rojeru_san.rsbutton.RSButtonRoundEffect up4;
    private rojeru_san.rslabel.RSLabelBorderRound usri;
    // End of variables declaration//GEN-END:variables
}
